apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-vol
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /var/nfs
    server: 172.18.82.25
