kind:               PersistentVolumeClaim
apiVersion:         v1
metadata:
  name:             webserverpvc2
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage:      10Gi
