kind:               PersistentVolumeClaim
apiVersion:         v1
metadata:
  name:             webserverpvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage:      200Mi
