kind:                          Deployment
apiVersion:                    extensions/v1beta1
metadata:
  name:                        webserver-with-pv2
spec:
  replicas:                    1
  template:
    metadata:
      labels:
        app:                   webserver2
    spec:
      containers:
      - name:                  apache-php5
        image:                 risangsaputra/apache2-php5.6
        ports:
        - containerPort:       80
        volumeMounts:
        - mountPath:           "/var/www/html"
          name:                webservercontent
      volumes:
      - name:                  webservercontent
        persistentVolumeClaim:
          claimName:           webserverpvc2
---
apiVersion: v1
kind: Service
metadata:
  name: webserver2-svc
spec:
  ports:
     -  port: 80
        nodePort: 32279
        protocol: TCP
        targetPort: 80
  selector:
    app: webserver2
  type: NodePort
