kind:                          Deployment
apiVersion:                    extensions/v1beta1
metadata:
  name:                        webserver-with-pv
spec:
  replicas:                    1
  template:
    metadata:
      labels:
        app:                   webserver
    spec:
      containers:
      - name:                  apache-php5
        image:                 risangsaputra/apache2-php5.6
        ports:
        - containerPort:       80
        volumeMounts:
        - mountPath:           "/usr/share/nginx/html"
          name:                webservercontent
      volumes:
      - name:                  webservercontent
        persistentVolumeClaim:
          claimName:           webserverpvc
